#
# Travis CI configuration file for CUPS.
#
# Copyright Â© 2018 by Apple Inc.
#
# Licensed under Apache License v2.0.  See the file "LICENSE" for more
# information.
#

language: c

matrix:
  include:
    # Linux-specific build stuff
    - dist: trusty
      sudo: required
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libavahi-client-dev libgnutls28-dev libkrb5-dev libnss-mdns libpam-dev libsystemd-dev libusb-1.0-0-dev zlib1g-dev

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode10

script: ./configure && make check
